# This is where I always go
[[mgr.append_keymap]]
on = ["g", "C"]
run = "cd ~/Code"
desc = "Go ~/Code"

[[mgr.append_keymap]]
on = ["g", "D"]
run = "cd ~/Desktop"
desc = "Go ~/Desktop"

# Custom linemode from init.lua
[[mgr.append_keymap]]
on = ["m", "S"]
run = "linemode size_and_mtime"
desc = "Linemode: size_and_mtime"

# I'm used to having zoxide on `z`, so I switched fzf to `Z`
[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"

# Zoom plugin
[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

# Chmod plugin
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

# What size plugin
[[mgr.prepend_keymap]]
on = [ "n", "s" ]
run  = "plugin what-size"
desc = "Calc size of selection or cwd"

# Compess plugin
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"
